---
abstract: 'A Set of Discrete Finite Automata'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Set-FA
provides:
  Set::FA:
    file: lib/Set/FA.pm
    version: 1.06
  Set::FA::Element:
    file: lib/Set/FA/Element.pm
    version: 1.06
requires:
  Capture::Tiny: 0.1
  Hash::FieldHash: 0.1
  Set::Object: 1.28
  attributes: 0.12
  parent: 0.224
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.06
